### ISSUE TITLE
stuck into the log in screen 

### ISSUE THREAD

**Issue by heliohexcore28** [theVakhovskeIsTaken/holoiso#204]
hii i installed just an hour ago holoiso but now im stuck into a log in screen on a terminal interface and even if i do the log in im still blocked here sorry for the english but im italian 
![WIN_20220526_21_43_46_Pro](https://user-images.githubusercontent.com/106332589/170565263-26b463f6-349c-4840-a8ec-12cf01ab1786.jpg)

**Comment by thekidflipper** [comment]
I have this same issue now. Doesn't seem like the desktop environment is loading for us

**Comment by heliohexcore28** [comment]
i really dont know whats i have to do 
if a find a solution i will comment here

**Comment by theVakhovskeIsTaken** [comment]
You should've installed full installation, not the base one.

Either run `sudo pacman -S holoiso-main gamescope mesa lib32-mesa vulkan-radeon lib32-vulkan-radeom` or start the installation again

**Comment by thekidflipper** [comment]
Hello! Thanks for the response. But when i try to install the main one, it freezes at the first part 
![Uploading 16536916690041278998493621391969.jpg…]()

**Comment by thekidflipper** [comment]
FYI for specs,
Ryzen 5600x
B550m
GTX 1660s

**Comment by theVakhovskeIsTaken** [comment]
> FYI for specs,
> Ryzen 5600x
> B550m
> GTX 1660s

oh really....
Reinstall the ISO fully then, now choosing deckperience and nvidia drivers.

**Comment by thekidflipper** [comment]
> > FYI for specs,
> > Ryzen 5600x
> > B550m
> > GTX 1660s
> 
> oh really.... Reinstall the ISO fully then, now choosing deckperience and nvidia drivers.

Hello, i tried this, it would just freeze like in my previous comment

**Comment by theVakhovskeIsTaken** [comment]
> > > FYI for specs,
> > > Ryzen 5600x
> > > B550m
> > > GTX 1660s
> > 
> > oh really.... Reinstall the ISO fully then, now choosing deckperience and nvidia drivers.
> 
> Hello, i tried this, it would just freeze like in my previous comment 

Download the newer one, because earlier one had broken modesetting

**Comment by thekidflipper** [comment]
> > > > FYI for specs,
> > > > Ryzen 5600x
> > > > B550m
> > > > GTX 1660s
> > > 
> > > 
> > > oh really.... Reinstall the ISO fully then, now choosing deckperience and nvidia drivers.
> > 
> > 
> > Hello, i tried this, it would just freeze like in my previous comment
> 
> Download the newer one, because earlier one had broken modesetting

I will try! Thank you! But for FYI, this was where Id get stuck! 
![Uploading IMG_20220528_065910.jpg…]()

**Comment by thekidflipper** [comment]
![IMG_20220528_065910](https://user-images.githubusercontent.com/39328747/170798848-ebf9acc4-e50f-4a8e-ab90-dd49b572089c.jpg)

Hello, with the latest release, i still get stuck at this part of the installation.

**Comment by theVakhovskeIsTaken** [comment]
> ![IMG_20220528_065910](https://user-images.githubusercontent.com/39328747/170798848-ebf9acc4-e50f-4a8e-ab90-dd49b572089c.jpg)
> 
> Hello, with the latest release, i still get stuck at this part of the installation.

Boot as core/linux.

**Comment by thekidflipper** [comment]
Hello, when I boot as core/linux, it will only give me the command line like the original Issue. This is with the latest snapshot
